# Generated by Django 5.1.2 on 2024-11-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='Essa categoria não possui descrição'),
        ),
    ]
